actors:
  maril:
    image_url: /images/actors/m.png
    name: maril
    url: http://twitter.com/marilatelier
  
author: maril
description: 整理整頓 Podcast
description_long: 整理整頓大好きな人間が秀才に憧れてアタマやカラダを整えます。
email: mariltotonoel@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: totonoel
itunes_podcast_url:
keywords: life,study,learn,bodymake,health,notebook
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: まりるととのえる
url: https://maril00.github.io/totonoel/

theme: jekyll-theme-minimal